development:
  host: localhost
  database: represent_development

test:
  host: localhost
  database: represent_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true